"""Mermaid diagrams of labmate's LangGraph graphs, generated from the compiled graphs.

``make graphs`` writes them to ``docs/graphs.md`` (GitHub renders Mermaid), so the
diagrams can't drift from the code. :data:`ASK_OVERVIEW` is the hand-drawn overview of
the ask agent with its two subgraphs expanded; the dashboard animates it.
"""

from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace
from typing import Any

from labmate.config import Config

ASK_OVERVIEW = """flowchart TB
    q([question]) --> understand
    understand -->|off topic| abstain
    understand -->|ambiguous| clarify{{"✋ clarify<br/>(interrupt)"}}
    understand --> plan
    clarify --> plan
    plan -->|"Send × k<br/>(one per query)"| research_retrieve
    subgraph research ["research (subgraph, per query)"]
        research_retrieve["retrieve<br/>hybrid: BM25 + dense, RRF<br/>tier 1 first"]
        research_grade["grade<br/>(judge model)"]
        research_retrieve --> research_grade
        research_grade -->|not enough| research_rewrite["rewrite query<br/>+ widen tier"]
        research_rewrite --> research_retrieve
    end
    research_grade -->|enough / budget used| conflicts["conflict check<br/>dissertation vs papers"]
    conflicts -->|no evidence| abstain
    conflicts --> answer["answer<br/>cited sentences"]
    answer --> verify_judge
    subgraph verify ["verify (fact-check subgraph)"]
        verify_judge["judge<br/>(critic model)"] -->|unsupported| verify_rewrite[rewrite]
        verify_rewrite --> verify_judge
    end
    verify_judge --> finalize["finalize<br/>numbered citations"]
    finalize --> a([answer + memory])
    abstain --> a
"""
"""The ask agent with its subgraphs expanded (node ids match the dashboard's events)."""

PAPER2FLOW_OVERVIEW = """flowchart TB
    p([paper]) --> ingest --> publication --> route
    route --> fan1{{"Send × sections"}} --> extract[extract claims] --> outline
    outline --> gate{{"✋ human gate<br/>(interrupt)"}}
    gate --> fan2{{"Send × 4 blocks"}} --> write
    write --> judge
    subgraph factcheck ["fact-check loop"]
        judge -->|unsupported| rewrite --> judge
    end
    judge --> post[post text] --> flow_overview["flow: overview<br/>(orchestrator)"]
    flow_overview --> fan3{{"Send × steps"}} --> flow_detail["flow: details<br/>(workers)"]
    flow_detail --> render --> out([overview.pdf + post.pdf])
"""
"""The paper2flow workflow as its LangGraph engine runs it."""


def _stub() -> Any:
    """Just enough of a session for the graph builders (nodes are never run)."""
    return SimpleNamespace(config=Config(), llm=None, judge=None, switcher=None, workers=1)


def generated_diagrams() -> dict[str, str]:
    """Mermaid source of every compiled graph, as LangGraph draws it.

    Returns:
        Title to Mermaid source.
    """
    from labmate.ask.agent import build_agent  # noqa: PLC0415 - optional dependencies
    from labmate.ask.graph import build_graph, build_research  # noqa: PLC0415
    from labmate.ask.verify import build_verifier  # noqa: PLC0415
    from labmate.paper2flow.engines.langgraph_engine import (  # noqa: PLC0415
        build_graph as paper2flow_graph,
    )

    stub = _stub()
    from labmate.core.model import LLM  # noqa: PLC0415

    agent_stub = SimpleNamespace(
        llm=LLM(None, "model"),  # type: ignore[arg-type]
        index=None,
        embedder=None,
        config=Config(),
    )
    return {
        "paper2flow (LangGraph engine)": paper2flow_graph(
            stub, None, None, None, None, "", False, False
        )
        .compile()
        .get_graph()
        .draw_mermaid(),
        "ask": build_graph(stub).compile().get_graph().draw_mermaid(),
        "ask · research subgraph (one per planned query)": build_research(stub)
        .get_graph()
        .draw_mermaid(),
        "ask · verify subgraph (shared fact-check loop)": build_verifier(None, None, None)  # type: ignore[arg-type]
        .get_graph()
        .draw_mermaid(),
        "ask · prebuilt baseline (LangChain create_agent)": build_agent(agent_stub)  # type: ignore[arg-type]
        .get_graph()
        .draw_mermaid(),
    }


def diagrams_markdown() -> str:
    """The diagrams page: overviews first, then the generated graphs.

    Returns:
        Markdown with Mermaid blocks.
    """
    parts = [
        "# labmate graphs",
        "",
        "Generated by `make graphs` from the compiled LangGraph graphs; don't edit by hand.",
        "",
        "## ask: overview",
        "",
        "```mermaid",
        ASK_OVERVIEW.rstrip(),
        "```",
        "",
        "## paper2flow: overview",
        "",
        "```mermaid",
        PAPER2FLOW_OVERVIEW.rstrip(),
        "```",
    ]
    for title, source in generated_diagrams().items():
        parts += ["", f"## {title}", "", "```mermaid", source.rstrip(), "```"]
    return "\n".join(parts) + "\n"


def write_diagrams(out: Path) -> Path:
    """Write the diagrams page.

    Args:
        out: Markdown file.

    Returns:
        ``out``.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(diagrams_markdown())
    return out
