"""Mermaid diagrams of labmate's chains and graphs, generated from the code.

``make graphs`` writes them to ``docs/graphs.md`` (GitHub renders Mermaid), so the
diagrams can't drift from the code: LangChain draws every chain and LangGraph every graph
(``get_graph().draw_mermaid()``).
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from types import SimpleNamespace

from labmate.config import Config

_STEP_NOTE = re.compile(r"<hr/><small><em>step = [\w.]+</em></small>")
"""The metadata note LangChain adds to every named step (the step name, again)."""


def generated_diagrams() -> dict[str, str]:
    """Mermaid source of every compiled chain and graph, as LangChain and LangGraph draw it.

    Returns:
        Title to Mermaid source.
    """
    from labmate.ask.agent import build_agent  # noqa: PLC0415 - optional dependencies
    from labmate.ask.graph import build_graph  # noqa: PLC0415
    from labmate.core.chat import chat_model  # noqa: PLC0415
    from labmate.cv2job.chain import build_cv2job  # noqa: PLC0415
    from labmate.paper2flow.chain import build_paper2flow  # noqa: PLC0415
    from labmate.paper2post.chain import build_paper2post  # noqa: PLC0415

    config = Config()
    model = chat_model(config, config.models.text)  # builds the client only; nothing is called
    stub = SimpleNamespace(config=config, writer=model, judge=model, index=None, embedder=None)
    return {
        "paper2flow (chain)": _STEP_NOTE.sub("", build_paper2flow(stub).get_graph().draw_mermaid()),  # type: ignore[arg-type]
        "paper2post (chain)": _STEP_NOTE.sub("", build_paper2post(stub).get_graph().draw_mermaid()),  # type: ignore[arg-type]
        "cv2job (chain with one agent step)": build_cv2job(
            config, lambda question: "", Path("."), date.today()
        )
        .get_graph()
        .draw_mermaid(),
        "ask (graph)": build_graph(stub).compile().get_graph().draw_mermaid(),  # type: ignore[arg-type]
        "ask (agent)": build_agent(stub).get_graph().draw_mermaid(),  # type: ignore[arg-type]
    }


def diagrams_markdown() -> str:
    """The diagrams page.

    Returns:
        Markdown with one Mermaid block per chain and graph.
    """
    parts = ["# labmate graphs", "", "Generated by `make graphs`; don't edit by hand."]
    for title, source in generated_diagrams().items():
        parts += ["", f"## {title}", "", "```mermaid", source.rstrip(), "```"]
    return "\n".join(parts) + "\n"


def write_diagrams(out: Path) -> Path:
    """Write the diagrams page.

    Args:
        out: Markdown file.

    Returns:
        ``out``.
    """
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(diagrams_markdown())
    return out
